server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /resume.pdf {
        add_header Content-Disposition 'attachment; filename="Alison-Goncalves-Resume.pdf"';
    }

    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;
}
