import type { Metadata } from 'next'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import Markdown, { type Components } from 'react-markdown'
import { ApiError, blogApi } from '../../../blog/api'
import { Comments } from '../../../blog/components/Comments'
import { CoverImage } from '../../../blog/components/CoverImage'
import { MarkdownImage } from '../../../blog/components/MarkdownImage'
import { ShareButtons } from '../../../blog/components/ShareButtons'
import { ViewRegistrar } from '../../../blog/components/ViewRegistrar'
import { blogListPath } from '../../../blog/routes'
import { blogPostUrl } from '../../../blog/url'
import { Section } from '../../../components/Section'
import { LiveCursorOverlay } from '../../../live-cursors/components/LiveCursorOverlay'
import { JsonLd } from '../../../seo/JsonLd'
import { PERSON_ID, SITE_ORIGIN, SITE_TITLE } from '../../../seo/site'

function formatDate(iso: string) {
  return new Date(iso).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })
}

// Draft posts generated by the "Get top trends" agent (server/src/trends)
// come back with citation artifacts like (cite index="1-1">...</cite> —
// the Admin's markdown editor never produces raw HTML itself, so any raw
// tag in a Post's content is treated as noise and unwrapped (tag removed,
// text kept) rather than rendered literally as bracketed text. The `:`
// right after the tag name in an autolink like <https://x.com> keeps this
// from matching CommonMark autolinks.
function stripRawHtmlTags(markdown: string) {
  return markdown
    .replace(/\([a-zA-Z][a-zA-Z0-9]*\s+[^()<>]*">/g, '')
    .replace(/<\/?[a-zA-Z][a-zA-Z0-9]*(\s[^<>]*)?>/g, '')
}

// Renders the post's markdown `content` with this site's own theme tokens
// instead of react-markdown's unstyled defaults — kept local to the Blog
// route rather than a shared "prose" stylesheet, since nothing else in
// the public site renders arbitrary markdown. Headings are serif like the
// rest of the site; running text stays in the sans.
//
// A `#` in the post body renders as an h2 styled like an h1: the post title
// in the header is the page's one h1.
const markdownComponents: Components = {
  h1: (props) => (
    <h2 className="mt-14 mb-5 font-serif text-[clamp(2rem,3.5vw,3rem)] leading-none font-normal tracking-[-0.05em] first:mt-0" {...props} />
  ),
  h2: (props) => (
    <h2 className="mt-14 mb-5 font-serif text-[clamp(1.75rem,3vw,2.5rem)] leading-none font-normal tracking-[-0.05em] first:mt-0" {...props} />
  ),
  h3: (props) => (
    <h3 className="mt-10 mb-4 font-serif text-[clamp(1.4rem,2.2vw,1.9rem)] leading-tight font-normal tracking-[-0.04em]" {...props} />
  ),
  p: (props) => <p className="mb-6 text-[1.1rem] leading-[1.6]" {...props} />,
  a: (props) => (
    <a
      className="underline decoration-1 underline-offset-[0.16em] hover:decoration-2"
      target="_blank"
      rel="noreferrer"
      {...props}
    />
  ),
  strong: (props) => <strong className="font-semibold" {...props} />,
  em: (props) => <em {...props} />,
  ul: (props) => <ul className="mb-6 list-disc space-y-2 pl-6 text-[1.1rem] leading-[1.6]" {...props} />,
  ol: (props) => <ol className="mb-6 list-decimal space-y-2 pl-6 text-[1.1rem] leading-[1.6]" {...props} />,
  li: (props) => <li {...props} />,
  blockquote: (props) => (
    <blockquote className="mb-6 border-l-2 border-ink pl-5 font-serif text-[1.3rem] leading-[1.35] italic" {...props} />
  ),
  img: (props) => <MarkdownImage {...props} />,
  code: (props) => (
    <code className="bg-surface-raised px-1.5 py-0.5 font-mono text-[0.85em]" {...props} />
  ),
  hr: (props) => <hr className="my-10 border-line" {...props} />,
}

interface Props {
  params: Promise<{ slug: string }>
}

// Replaces the entire ADR 0011/0012 meta-tag-injection mechanism — the
// server genuinely renders this page per Post, so Next's generateMetadata
// can just read the same data. See docs/adr/0013.
export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params
  const post = await blogApi.getPost(slug, { cache: 'no-store' }).catch(() => null)
  if (!post) return {}

  const canonical = blogPostUrl(post.slug)
  const images = post.coverImageUrl ? [{ url: post.coverImageUrl, alt: post.title }] : undefined

  return {
    title: post.title,
    description: post.excerpt,
    alternates: { canonical },
    openGraph: {
      type: 'article',
      url: canonical,
      title: post.title,
      description: post.excerpt,
      siteName: SITE_TITLE,
      images,
      publishedTime: post.publishedAt ?? undefined,
      modifiedTime: post.updatedAt,
      authors: [SITE_ORIGIN],
    },
    twitter: {
      card: post.coverImageUrl ? 'summary_large_image' : 'summary',
      title: post.title,
      description: post.excerpt,
      images,
    },
  }
}

const backLinkClass = 'mono-label underline decoration-1 underline-offset-[0.16em] hover:decoration-2'

// The same two-column rail-and-body grid every Section uses, without the
// big headline — the post's own h1 in the header above already is one.
const railClass =
  'gap-[clamp(1.5rem,5vw,7rem)] border-b border-rule px-(--gutter) py-[clamp(3rem,6vw,6rem)] min-[721px]:grid min-[721px]:grid-cols-[minmax(9rem,0.33fr)_minmax(0,1fr)]'

export default async function BlogPostPage({ params }: Props) {
  const { slug } = await params

  // Next memoizes identical fetch() calls within one render pass, so this
  // doesn't double-hit the API even though generateMetadata above already
  // fetched the same URL — verified in Phase 3's manual testing.
  const backToBlog = await blogListPath()

  let post
  try {
    post = await blogApi.getPost(slug, { cache: 'no-store' })
  } catch (err) {
    if (err instanceof ApiError && err.status === 404) notFound()
    return (
      <main className="border-b border-rule px-(--gutter) py-[clamp(2rem,4vw,4rem)]">
        <Link href={backToBlog} className={backLinkClass}>
          ← Back to Blog
        </Link>
        <p className="mt-12 text-red-700">Could not load this post right now. Please try again later.</p>
      </main>
    )
  }

  const comments = await blogApi.listComments(slug, { cache: 'no-store' })
  const sanitizedContent = stripRawHtmlTags(post.content)
  const canonical = blogPostUrl(post.slug)

  return (
    <main>
      <JsonLd
        data={{
          '@context': 'https://schema.org',
          '@type': 'BlogPosting',
          headline: post.title,
          description: post.excerpt,
          url: canonical,
          mainEntityOfPage: canonical,
          ...(post.coverImageUrl && { image: post.coverImageUrl }),
          ...(post.publishedAt && { datePublished: post.publishedAt }),
          dateModified: post.updatedAt,
          author: { '@type': 'Person', '@id': PERSON_ID, name: 'Alison Rafael Marinho Gonçalves', url: SITE_ORIGIN },
        }}
      />
      <ViewRegistrar slug={post.slug} />
      <LiveCursorOverlay room={`post:${post.slug}`} key={post.slug} />

      <header
        className={`grid border-b border-rule ${
          post.coverImageUrl
            ? 'min-[721px]:min-h-[min(48rem,calc(100svh-3.6rem))] min-[721px]:grid-cols-[minmax(0,1.12fr)_minmax(15rem,0.88fr)]'
            : ''
        }`}
      >
        <div className="flex flex-col items-start justify-between px-(--gutter) pt-[clamp(2rem,6vw,6rem)] pb-[clamp(2rem,4vw,4rem)] max-[720px]:min-h-[30rem]">
          <div className="flex w-full flex-wrap items-baseline justify-between gap-x-6 gap-y-2">
            <Link href={backToBlog} className={backLinkClass}>
              ← Back to Blog
            </Link>
            <p className="mono-label text-ink-dim">
              {post.publishedAt && `${formatDate(post.publishedAt)} / `}
              {post.viewCount.toLocaleString('en-US')} views
            </p>
          </div>

          <h1 className="mt-[clamp(3rem,8vw,7rem)] mb-[clamp(3rem,6vw,5rem)] max-w-[18ch] text-[clamp(2.25rem,5.6vw,6rem)] leading-[0.9] font-normal tracking-[-0.075em] break-words">
            {post.title}
          </h1>

          <p className="max-w-xl font-serif text-[clamp(1.15rem,1.65vw,1.55rem)] leading-[1.25]">{post.excerpt}</p>
        </div>

        {post.coverImageUrl && <CoverImage src={post.coverImageUrl} alt={post.title} />}
      </header>

      <section className={railClass}>
        <p className="mono-label mb-14 text-ink-dim min-[721px]:mb-0">01 / Article</p>
        <article className="max-w-[46rem] min-w-0">
          <Markdown components={markdownComponents}>{sanitizedContent}</Markdown>

          <ShareButtons slug={post.slug} title={post.title} />
        </article>
      </section>

      <Section index="02 / Discussion" title="Comments.">
        <div className="max-w-[46rem]">
          <Comments slug={post.slug} initialComments={comments} />
        </div>
      </Section>
    </main>
  )
}
