import { ArrowLeft, Calendar, Eye } from 'lucide-react'
import type { Metadata } from 'next'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import Markdown, { type Components } from 'react-markdown'
import { ApiError, blogApi } from '../../../blog/api'
import { Comments } from '../../../blog/components/Comments'
import { MarkdownImage } from '../../../blog/components/MarkdownImage'
import { ShareButtons } from '../../../blog/components/ShareButtons'
import { ViewRegistrar } from '../../../blog/components/ViewRegistrar'
import { Reveal } from '../../../components/Reveal'

const SITE_NAME = 'Alison Rafael Marinho Gonçalves — Full-Stack Engineer'

function formatDate(iso: string) {
  return new Date(iso).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })
}

// Draft posts generated by the "Get top trends" agent (server/src/trends)
// come back with citation artifacts like (cite index="1-1">...</cite> —
// the Admin's markdown editor never produces raw HTML itself, so any raw
// tag in a Post's content is treated as noise and unwrapped (tag removed,
// text kept) rather than rendered literally as bracketed text. The `:`
// right after the tag name in an autolink like <https://x.com> keeps this
// from matching CommonMark autolinks.
function stripRawHtmlTags(markdown: string) {
  return markdown
    .replace(/\([a-zA-Z][a-zA-Z0-9]*\s+[^()<>]*">/g, '')
    .replace(/<\/?[a-zA-Z][a-zA-Z0-9]*(\s[^<>]*)?>/g, '')
}

// Renders the post's markdown `content` with this site's own theme tokens
// instead of react-markdown's unstyled defaults — kept local to the Blog
// route rather than a shared "prose" stylesheet, since nothing else in
// the public site renders arbitrary markdown.
const markdownComponents: Components = {
  h1: (props) => <h1 className="mt-10 mb-4 text-3xl font-bold text-ink first:mt-0" {...props} />,
  h2: (props) => <h2 className="mt-10 mb-4 text-2xl font-semibold text-ink first:mt-0" {...props} />,
  h3: (props) => <h3 className="mt-8 mb-3 text-xl font-semibold text-ink" {...props} />,
  p: (props) => <p className="mb-5 leading-relaxed text-ink-dim" {...props} />,
  a: (props) => (
    <a
      className="text-accent underline decoration-accent/40 underline-offset-2 hover:decoration-accent"
      target="_blank"
      rel="noreferrer"
      {...props}
    />
  ),
  strong: (props) => <strong className="font-semibold text-ink" {...props} />,
  em: (props) => <em className="text-ink" {...props} />,
  ul: (props) => <ul className="mb-5 list-disc space-y-1.5 pl-6 text-ink-dim" {...props} />,
  ol: (props) => <ol className="mb-5 list-decimal space-y-1.5 pl-6 text-ink-dim" {...props} />,
  li: (props) => <li className="leading-relaxed" {...props} />,
  blockquote: (props) => (
    <blockquote className="mb-5 border-l-2 border-accent/40 pl-4 text-ink-dim italic" {...props} />
  ),
  img: (props) => <MarkdownImage {...props} />,
  code: (props) => (
    <code className="rounded bg-surface-raised px-1.5 py-0.5 font-mono text-[0.85em] text-accent" {...props} />
  ),
  hr: (props) => <hr className="my-8 border-line" {...props} />,
}

interface Props {
  params: Promise<{ slug: string }>
}

// Replaces the entire ADR 0011/0012 meta-tag-injection mechanism — the
// server genuinely renders this page per Post, so Next's generateMetadata
// can just read the same data. See docs/adr/0013.
export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params
  const post = await blogApi.getPost(slug, { cache: 'no-store' }).catch(() => null)
  if (!post) return {}

  const canonical = `/blog/${post.slug}`
  const images = post.coverImageUrl ? [{ url: post.coverImageUrl, alt: post.title }] : undefined

  return {
    title: post.title,
    description: post.excerpt,
    alternates: { canonical },
    openGraph: {
      type: 'article',
      url: canonical,
      title: post.title,
      description: post.excerpt,
      siteName: SITE_NAME,
      images,
      publishedTime: post.publishedAt ?? undefined,
    },
    twitter: {
      card: post.coverImageUrl ? 'summary_large_image' : 'summary',
      title: post.title,
      description: post.excerpt,
      images,
    },
  }
}

export default async function BlogPostPage({ params }: Props) {
  const { slug } = await params

  // Next memoizes identical fetch() calls within one render pass, so this
  // doesn't double-hit the API even though generateMetadata above already
  // fetched the same URL — verified in Phase 3's manual testing.
  let post
  try {
    post = await blogApi.getPost(slug, { cache: 'no-store' })
  } catch (err) {
    if (err instanceof ApiError && err.status === 404) notFound()
    return (
      <main className="mx-auto max-w-3xl px-6 py-16">
        <Link
          href="/blog"
          className="mb-8 inline-flex items-center gap-1.5 text-sm text-ink-dim transition-colors hover:text-accent"
        >
          <ArrowLeft size={14} />
          Back to Blog
        </Link>
        <Reveal>
          <p className="text-sm text-red-400">Could not load this post right now. Please try again later.</p>
        </Reveal>
      </main>
    )
  }

  const comments = await blogApi.listComments(slug, { cache: 'no-store' })
  const sanitizedContent = stripRawHtmlTags(post.content)

  return (
    <main className="mx-auto max-w-3xl px-6 py-16">
      <ViewRegistrar slug={post.slug} />
      <Link
        href="/blog"
        className="mb-8 inline-flex items-center gap-1.5 text-sm text-ink-dim transition-colors hover:text-accent"
      >
        <ArrowLeft size={14} />
        Back to Blog
      </Link>

      <Reveal>
        <article>
          <header className="mb-8">
            <p className="flex flex-wrap items-center gap-x-4 gap-y-1.5 font-mono text-xs text-ink-dim">
              {post.publishedAt && (
                <span className="flex items-center gap-1.5">
                  <Calendar size={12} className="text-accent" />
                  {formatDate(post.publishedAt)}
                </span>
              )}
              <span className="flex items-center gap-1.5">
                <Eye size={12} className="text-accent" />
                {post.viewCount.toLocaleString('en-US')} views
              </span>
            </p>
            <h1 className="mt-3 text-3xl font-extrabold tracking-tight text-ink sm:text-4xl">{post.title}</h1>
          </header>

          {post.coverImageUrl && (
            <div className="mb-8 overflow-hidden rounded-xl border border-line">
              <img
                src={post.coverImageUrl}
                alt=""
                loading="lazy"
                className="block max-h-[420px] w-full object-cover"
              />
            </div>
          )}

          <Markdown components={markdownComponents}>{sanitizedContent}</Markdown>
        </article>

        <ShareButtons slug={post.slug} title={post.title} />

        <hr className="my-12 border-line" />
        <Comments slug={post.slug} initialComments={comments} />
      </Reveal>
    </main>
  )
}
