import { ArrowLeft, Calendar } from 'lucide-react'
import { type ComponentProps, useEffect, useMemo, useState } from 'react'
import Markdown, { type Components } from 'react-markdown'
import { Link, useParams } from 'react-router-dom'
import { Footer } from '../../components/Footer'
import { Nav } from '../../components/Nav'
import { Reveal } from '../../components/Reveal'
import { useResumeContent } from '../../i18n'
import { ApiError, blogApi, type Post } from '../api'

function formatDate(iso: string) {
  return new Date(iso).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })
}

// Draft posts generated by the "Get top trends" agent (server/src/trends)
// come back with citation artifacts like <cite index="1-1">...</cite> —
// the Admin's markdown editor never produces raw HTML itself, so any raw
// tag in a Post's content is treated as noise and unwrapped (tag removed,
// text kept) rather than rendered literally as bracketed text. The `:`
// right after the tag name in an autolink like <https://x.com> keeps this
// from matching CommonMark autolinks.
function stripRawHtmlTags(markdown: string) {
  return markdown
    .replace(/\([a-zA-Z][a-zA-Z0-9]*\s+[^()<>]*">/g, '')
    .replace(/<\/?[a-zA-Z][a-zA-Z0-9]*(\s[^<>]*)?>/g, '')
}

function MarkdownImage(props: ComponentProps<'img'>) {
  const [loaded, setLoaded] = useState(false)
  return (
    <span
      className={`mb-5 block overflow-hidden rounded-xl border border-line bg-surface-raised ${loaded ? '' : 'min-h-60'}`}
    >
      <img {...props} loading="lazy" className="block w-full rounded-xl" onLoad={() => setLoaded(true)} />
    </span>
  )
}

// Renders the post's markdown `content` with this site's own theme tokens
// instead of react-markdown's unstyled defaults — kept local to the Blog
// bundle rather than a shared "prose" stylesheet, since nothing else in
// the public site renders arbitrary markdown.
const markdownComponents: Components = {
  h1: (props) => <h1 className="mt-10 mb-4 text-3xl font-bold text-ink first:mt-0" {...props} />,
  h2: (props) => <h2 className="mt-10 mb-4 text-2xl font-semibold text-ink first:mt-0" {...props} />,
  h3: (props) => <h3 className="mt-8 mb-3 text-xl font-semibold text-ink" {...props} />,
  p: (props) => <p className="mb-5 leading-relaxed text-ink-dim" {...props} />,
  a: (props) => (
    <a
      className="text-accent underline decoration-accent/40 underline-offset-2 hover:decoration-accent"
      target="_blank"
      rel="noreferrer"
      {...props}
    />
  ),
  strong: (props) => <strong className="font-semibold text-ink" {...props} />,
  em: (props) => <em className="text-ink" {...props} />,
  ul: (props) => <ul className="mb-5 list-disc space-y-1.5 pl-6 text-ink-dim" {...props} />,
  ol: (props) => <ol className="mb-5 list-decimal space-y-1.5 pl-6 text-ink-dim" {...props} />,
  li: (props) => <li className="leading-relaxed" {...props} />,
  blockquote: (props) => (
    <blockquote className="mb-5 border-l-2 border-accent/40 pl-4 text-ink-dim italic" {...props} />
  ),
  img: (props) => <MarkdownImage {...props} />,
  code: (props) => (
    <code className="rounded bg-surface-raised px-1.5 py-0.5 font-mono text-[0.85em] text-accent" {...props} />
  ),
  hr: (props) => <hr className="my-8 border-line" {...props} />,
}

type Status = { kind: 'loading' } | { kind: 'notFound' } | { kind: 'error' } | { kind: 'ready'; post: Post }

export function BlogPostPage() {
  const { slug } = useParams<{ slug: string }>()
  const content = useResumeContent()
  const [status, setStatus] = useState<Status>({ kind: 'loading' })
  const sanitizedContent = useMemo(
    () => (status.kind === 'ready' ? stripRawHtmlTags(status.post.content) : ''),
    [status],
  )

  useEffect(() => {
    if (!slug) return
    let cancelled = false
    setStatus({ kind: 'loading' })
    blogApi
      .getPost(slug)
      .then((post) => {
        if (!cancelled) setStatus({ kind: 'ready', post })
      })
      .catch((err: unknown) => {
        if (cancelled) return
        setStatus({ kind: err instanceof ApiError && err.status === 404 ? 'notFound' : 'error' })
      })
    return () => {
      cancelled = true
    }
  }, [slug])

  return (
    <div className="min-h-screen bg-surface text-ink">
      <Nav content={content} />
      <main className="mx-auto max-w-3xl px-6 py-16">
        <Link
          to="/blog"
          className="mb-8 inline-flex items-center gap-1.5 text-sm text-ink-dim transition-colors hover:text-accent"
        >
          <ArrowLeft size={14} />
          Back to Blog
        </Link>

        {status.kind === 'loading' && (
          <Reveal>
            <p className="text-sm text-ink-dim">Loading post…</p>
          </Reveal>
        )}

        {status.kind === 'error' && (
          <Reveal>
            <p className="text-sm text-red-400">Could not load this post right now. Please try again later.</p>
          </Reveal>
        )}

        {status.kind === 'notFound' && (
          <Reveal>
            <div className="rounded-lg border border-dashed border-line px-6 py-12 text-center">
              <p className="font-mono text-sm text-accent">404</p>
              <h1 className="mt-2 text-xl font-semibold text-ink">Post not found</h1>
              <p className="mt-2 text-sm text-ink-dim">
                This post doesn't exist or hasn't been published.{' '}
                <Link to="/blog" className="text-accent underline underline-offset-2">
                  Back to Blog
                </Link>
              </p>
            </div>
          </Reveal>
        )}

        {status.kind === 'ready' && (
          <Reveal>
            <article>
              <header className="mb-8">
                {status.post.publishedAt && (
                  <p className="flex items-center gap-1.5 font-mono text-xs text-ink-dim">
                    <Calendar size={12} className="text-accent" />
                    {formatDate(status.post.publishedAt)}
                  </p>
                )}
                <h1 className="mt-3 text-3xl font-extrabold tracking-tight text-ink sm:text-4xl">
                  {status.post.title}
                </h1>
              </header>

              <Markdown components={markdownComponents}>{sanitizedContent}</Markdown>
            </article>
          </Reveal>
        )}
      </main>
      <Footer content={content} />
    </div>
  )
}
