import type { AdminContent } from './types'

export const en: AdminContent = {
  panel: {
    title: 'Admin Panel',
    logout: 'Log out',
  },
  nav: {
    posts: 'Posts',
    settings: 'Settings',
  },
  login: {
    title: 'Admin Panel',
    subtitle: 'Sign in to manage the Blog.',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    submit: 'Log in',
    submitting: 'Logging in…',
    invalidCredentials: 'Incorrect email or password.',
    genericError: 'Failed to log in. Please try again.',
  },
  postList: {
    heading: 'Posts',
    newPost: 'New post',
    getTopTrends: 'Get top trends',
    loadError: 'Failed to load posts.',
    loading: 'Loading…',
    empty: 'No posts yet.',
    published: 'Published',
    draft: 'Draft',
    updatedAtPrefix: 'updated',
    edit: 'Edit',
    delete: 'Delete',
    deleteConfirm: (title) => `Delete "${title}"? This action cannot be undone.`,
  },
  trends: {
    heading: 'Top trends',
    subtitle: 'Trending software development topics, ranked by relevance to your skill set.',
    backToPosts: 'Back to posts',
    lastSearchedPrefix: 'Last searched',
    noSearchYet: 'No search yet — press "Search now" to find trending topics.',
    searchNow: 'Search now',
    newSearch: 'New search',
    discovering: 'Searching the web and ranking topics — this can take a minute…',
    discoverError: 'Failed to discover trends. Please try again.',
    empty: 'No trends found.',
    relevancePrefix: 'Why it fits:',
    selectedCount: (count) => `${count} selected`,
    createPosts: 'Create posts',
    creating: 'Creating drafts…',
    created: 'Draft created',
    failed: 'Failed',
    viewPost: 'View post',
  },
  editor: {
    newPostHeading: 'New post',
    editPostHeading: 'Edit post',
    titleLabel: 'Title',
    slugLabel: 'Slug',
    excerptLabel: 'Excerpt',
    contentLabel: 'Content',
    markdownPlaceholder: '# Write markdown here…',
    publishedLabel: 'Published',
    save: 'Save',
    saving: 'Saving…',
    cancel: 'Cancel',
    loadError: 'Failed to load the post.',
    saveError: 'Failed to save the post.',
  },
  settings: {
    heading: 'Settings',
    subtitle: 'Change the password for this account.',
    currentPasswordLabel: 'Current password',
    newPasswordLabel: 'New password',
    incorrectPassword: 'Incorrect current password.',
    changeError: 'Failed to change the password.',
    success: 'Password updated.',
    submit: 'Change password',
    submitting: 'Saving…',
  },
  common: {
    loading: 'Loading…',
  },
}
