import type { AdminContent } from './types'

export const en: AdminContent = {
  panel: {
    title: 'Admin Panel',
    logout: 'Log out',
  },
  nav: {
    posts: 'Posts',
    comments: 'Comments',
    settings: 'Settings',
    tools: 'Tools',
  },
  login: {
    title: 'Admin Panel',
    subtitle: 'Sign in to manage the Blog.',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    submit: 'Log in',
    submitting: 'Logging in…',
    invalidCredentials: 'Incorrect email or password.',
    genericError: 'Failed to log in. Please try again.',
  },
  postList: {
    heading: 'Posts',
    newPost: 'New post',
    loadError: 'Failed to load posts.',
    loading: 'Loading…',
    empty: 'No posts yet.',
    published: 'Published',
    draft: 'Draft',
    updatedAtPrefix: 'updated',
    edit: 'Edit',
    delete: 'Delete',
    deleteConfirm: (title) => `Delete "${title}"? This action cannot be undone.`,
  },
  trends: {
    heading: 'Top trends',
    subtitle: 'Trending software development topics, ranked by relevance to your skill set.',
    backToTools: 'Back to tools',
    lastSearchedPrefix: 'Last searched',
    noSearchYet: 'No search yet — press "Search now" to find trending topics.',
    searchNow: 'Search now',
    newSearch: 'New search',
    discovering: 'Searching the web and ranking topics — this can take a minute…',
    liveOutputHeading: 'Live output',
    discoverError: 'Failed to discover trends. Please try again.',
    empty: 'No trends found.',
    relevancePrefix: 'Why it fits:',
    selectedCount: (count) => `${count} selected`,
    createPosts: 'Create posts',
    creating: 'Creating drafts…',
    created: 'Draft created',
    failed: 'Failed',
    viewPost: 'View post',
  },
  editor: {
    newPostHeading: 'New post',
    editPostHeading: 'Edit post',
    titleLabel: 'Title',
    slugLabel: 'Slug',
    excerptLabel: 'Excerpt',
    contentLabel: 'Content',
    markdownPlaceholder: '# Write markdown here…',
    coverImageLabel: 'Cover image',
    coverImageUpload: 'Upload cover image',
    coverImageReplace: 'Replace',
    coverImageRemove: 'Remove',
    coverImageUploading: 'Uploading…',
    coverImageError: 'Cover image upload failed.',
    publishedLabel: 'Published',
    save: 'Save',
    saving: 'Saving…',
    cancel: 'Cancel',
    loadError: 'Failed to load the post.',
    saveError: 'Failed to save the post.',
  },
  comments: {
    heading: 'Comments',
    subtitle: 'Approve reader comments before they appear on the Blog.',
    filterAll: 'All',
    filterPending: 'Pending',
    filterApproved: 'Approved',
    filterRejected: 'Rejected',
    loading: 'Loading…',
    loadError: 'Failed to load comments.',
    empty: 'No comments.',
    emptyPending: 'Nothing awaiting moderation.',
    emailNote: 'visible to you only',
    replyTag: 'reply',
    onPostPrefix: 'on',
    approve: 'Approve',
    unapprove: 'Set pending',
    reject: 'Reject',
    delete: 'Delete',
    deleteConfirm: (name) => `Delete the comment by ${name}? This cannot be undone.`,
    actionError: 'That action failed. Please try again.',
  },
  settings: {
    heading: 'Settings',
    subtitle: 'Change the password for this account.',
    currentPasswordLabel: 'Current password',
    newPasswordLabel: 'New password',
    incorrectPassword: 'Incorrect current password.',
    changeError: 'Failed to change the password.',
    success: 'Password updated.',
    submit: 'Change password',
    submitting: 'Saving…',
    resumeProfileHeading: 'Resume Profile',
    resumeProfileSubtitle:
      'The facts behind your resume, cover letters, and generated resumes — edit as JSON.',
    resumeProfileLoading: 'Loading…',
    resumeProfileLoadError: 'Failed to load the Resume Profile.',
    resumeProfileInvalidJson: 'That’s not valid JSON — fix the syntax and try again.',
    resumeProfileSaveError: 'Failed to save the Resume Profile.',
    resumeProfileSuccess: 'Resume Profile saved — the public site will pick it up shortly.',
    resumeProfileSave: 'Save',
    resumeProfileSaving: 'Saving…',
  },
  tools: {
    heading: 'Tools',
    subtitle: 'Personal utilities to help with the job search and beyond.',
    coverLetterName: 'Cover Letter Generator',
    coverLetterDescription: 'Paste a job description and generate a cover letter based on your resume.',
    trendsName: 'Get Top Trends',
    trendsDescription: 'Discover trending software development topics ranked against your Tech Stack.',
    atsResumeName: 'ATS Resume Generator',
    atsResumeDescription: 'Draft an ATS-optimized resume from your profile and publish it as the site download.',
  },
  toolsCoverLetter: {
    heading: 'Cover Letter Generator',
    subtitle: 'Paste a job description below — Claude will write a cover letter grounded in your resume.',
    backToTools: 'Back to tools',
    jobDescriptionLabel: 'Job description',
    jobDescriptionPlaceholder: 'Paste the full job posting here…',
    generate: 'Generate',
    generating: 'Writing your cover letter…',
    generateError: 'Failed to generate a cover letter. Please try again.',
    resultHeading: 'Cover letter',
    copy: 'Copy',
    copied: 'Copied!',
    downloadPdf: 'Download PDF',
    empty: 'Paste a job description above and press Generate.',
  },
  toolsAtsResume: {
    heading: 'ATS Resume Generator',
    subtitle:
      'Paste a job description below — Claude will tailor a resume from your real experience, emphasizing what fits this job, without adding anything that isn’t already there.',
    backToTools: 'Back to tools',
    jobDescriptionLabel: 'Job description',
    jobDescriptionPlaceholder: 'Paste the full job posting here…',
    generate: 'Generate',
    generating: 'Writing your resume…',
    regenerate: 'Regenerate',
    generateError: 'Failed to generate a resume. Please try again.',
    contentLabel: 'Resume (Markdown)',
    approve: 'Approve & Publish',
    approving: 'Publishing…',
    approveError: 'Failed to publish the resume. Please try again.',
    approvedPrefix: 'Published',
    viewLive: 'View live resume',
    empty: 'Paste a job description above and press Generate.',
  },
  common: {
    loading: 'Loading…',
  },
}
