import type { AdminContent } from './types'

export const en: AdminContent = {
  panel: {
    title: 'Admin Panel',
    logout: 'Log out',
  },
  nav: {
    posts: 'Posts',
    settings: 'Settings',
  },
  login: {
    title: 'Admin Panel',
    subtitle: 'Sign in to manage the Blog.',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    submit: 'Log in',
    submitting: 'Logging in…',
    invalidCredentials: 'Incorrect email or password.',
    genericError: 'Failed to log in. Please try again.',
  },
  postList: {
    heading: 'Posts',
    newPost: 'New post',
    loadError: 'Failed to load posts.',
    loading: 'Loading…',
    empty: 'No posts yet.',
    published: 'Published',
    draft: 'Draft',
    updatedAtPrefix: 'updated',
    edit: 'Edit',
    delete: 'Delete',
    deleteConfirm: (title) => `Delete "${title}"? This action cannot be undone.`,
  },
  editor: {
    newPostHeading: 'New post',
    editPostHeading: 'Edit post',
    titleLabel: 'Title',
    slugLabel: 'Slug',
    excerptLabel: 'Excerpt',
    contentLabel: 'Content',
    markdownPlaceholder: '# Write markdown here…',
    publishedLabel: 'Published',
    save: 'Save',
    saving: 'Saving…',
    cancel: 'Cancel',
    loadError: 'Failed to load the post.',
    saveError: 'Failed to save the post.',
  },
  settings: {
    heading: 'Settings',
    subtitle: 'Change the password for this account.',
    currentPasswordLabel: 'Current password',
    newPasswordLabel: 'New password',
    incorrectPassword: 'Incorrect current password.',
    changeError: 'Failed to change the password.',
    success: 'Password updated.',
    submit: 'Change password',
    submitting: 'Saving…',
  },
  common: {
    loading: 'Loading…',
  },
}
