export interface AdminContent {
  panel: {
    title: string
    logout: string
  }
  nav: {
    blog: string
    posts: string
    comments: string
    observability: string
    accessLog: string
    tools: string
    coverLetter: string
    trends: string
    atsResume: string
    settings: string
    changePassword: string
    resumeProfile: string
    openMenu: string
    closeMenu: string
  }
  login: {
    title: string
    subtitle: string
    emailLabel: string
    passwordLabel: string
    submit: string
    submitting: string
    invalidCredentials: string
    genericError: string
  }
  postList: {
    heading: string
    newPost: string
    loadError: string
    loading: string
    empty: string
    published: string
    draft: string
    updatedAtPrefix: string
    edit: string
    delete: string
    deleteConfirm: (title: string) => string
  }
  trends: {
    heading: string
    subtitle: string
    lastSearchedPrefix: string
    noSearchYet: string
    searchNow: string
    newSearch: string
    discovering: string
    liveOutputHeading: string
    discoverError: string
    empty: string
    relevancePrefix: string
    selectedCount: (count: number) => string
    createPosts: string
    creating: string
    created: string
    failed: string
    viewPost: string
  }
  editor: {
    newPostHeading: string
    editPostHeading: string
    titleLabel: string
    slugLabel: string
    excerptLabel: string
    contentLabel: string
    markdownPlaceholder: string
    coverImageLabel: string
    coverImageUpload: string
    coverImageReplace: string
    coverImageRemove: string
    coverImageUploading: string
    coverImageError: string
    publishedLabel: string
    save: string
    saving: string
    cancel: string
    loadError: string
    saveError: string
  }
  comments: {
    heading: string
    subtitle: string
    filterAll: string
    filterPending: string
    filterApproved: string
    filterRejected: string
    loading: string
    loadError: string
    empty: string
    emptyPending: string
    emailNote: string
    replyTag: string
    onPostPrefix: string
    approve: string
    unapprove: string
    reject: string
    delete: string
    deleteConfirm: (name: string) => string
    actionError: string
  }
  accessLog: {
    heading: string
    subtitle: string
    days: (n: number) => string
    loading: string
    loadError: string
    empty: string
    pageViews: string
    uniqueIps: string
    perDay: string
    topPages: string
    topReferrers: string
    topNetworks: string
    noReferrers: string
    unknownNetwork: string
    filtersHeading: string
    hostPlaceholder: string
    pathPlaceholder: string
    ipPlaceholder: string
    apply: string
    clear: string
    filterByIp: string
    colTime: string
    colPage: string
    colVisitor: string
    colReferrer: string
    previous: string
    next: string
    pageOf: (page: number, pages: number, total: number) => string
    attribution: string
  }
  settings: {
    heading: string
    subtitle: string
    currentPasswordLabel: string
    newPasswordLabel: string
    incorrectPassword: string
    changeError: string
    success: string
    submit: string
    submitting: string
  }
  resumeProfile: {
    heading: string
    subtitle: string
    loading: string
    loadError: string
    saveError: string
    success: string
    save: string
    saving: string
    add: string
    remove: string
    moveUp: string
    moveDown: string
    sections: {
      basics: string
      links: string
      topSkills: string
      technologyGroups: string
      languages: string
      certifications: string
      experience: string
      projects: string
      education: string
    }
    fields: {
      name: string
      headline: string
      location: string
      phone: string
      email: string
      linkedin: string
      linkedinLabel: string
      github: string
      githubLabel: string
      website: string
      websiteLabel: string
      skill: string
      groupLabel: string
      groupItems: string
      technology: string
      languageName: string
      languageLevel: string
      certification: string
      company: string
      totalDuration: string
      emphasized: string
      roles: string
      role: string
      title: string
      period: string
      description: string
      projectName: string
      association: string
      skills: string
      school: string
      degree: string
    }
    items: {
      technologyGroup: string
      language: string
      experience: string
      project: string
      education: string
    }
  }
  toolsCoverLetter: {
    heading: string
    subtitle: string
    jobDescriptionLabel: string
    jobDescriptionPlaceholder: string
    generate: string
    generating: string
    generateError: string
    resultHeading: string
    copy: string
    copied: string
    downloadPdf: string
    empty: string
  }
  toolsAtsResume: {
    heading: string
    subtitle: string
    jobDescriptionLabel: string
    jobDescriptionPlaceholder: string
    generate: string
    generating: string
    regenerate: string
    generateError: string
    contentLabel: string
    approve: string
    approving: string
    approveError: string
    approvedPrefix: string
    viewLive: string
    empty: string
  }
  common: {
    loading: string
  }
}
